name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    uses: EasyDesk/workflows/.github/workflows/microservice-cicd.yml@master
    with:
      dotnet-version: 10.0.x
      warnings-as-errors: true
      main-project: src/SampleApi/SampleApi.csproj
      tests: |
        [
          "tests/SampleApi.UnitTests/SampleApi.UnitTests.csproj",
          "tests/SampleApi.IntegrationTests/SampleApi.IntegrationTests.csproj"
        ]
