name: GitHub Continuous Delivery

on:
  workflow_call:
    inputs:
      release-prefix:
        type: string
        required: false
        default: ${{ github.repository }}
    outputs:
      released:
        value: ${{ jobs.release.outputs.released == 'true' }}

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release-notification.outputs.released }}
    concurrency: release
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Checkout
        id: semver
        uses: EasyDesk/action-semver-checkout@v1
      - uses: actions/download-artifact@v5
        with:
          path: ${{ runner.temp }}/artifacts
      - id: zip
        name: Zip assets
        env:
          ZIP_OUTPUT_NAME: ${{ inputs.release-prefix }}_${{ steps.semver.outputs.version }}
        run: |
          ZIP_NAME="${ZIP_OUTPUT_NAME//\//_}.zip"
          zip -r "${ZIP_NAME}" "${{ runner.temp }}/artifacts"/*
          echo "output=${ZIP_NAME}" >> $GITHUB_OUTPUT
      - name: Release
        uses: EasyDesk/action-semver-release@v1
        with:
          version: ${{ steps.semver.outputs.version }}
          prerelease: ${{ steps.semver.outputs.is-github-prerelease }}
          prefix: ${{ inputs.release-prefix }}
          files: |
            ${{ steps.zip.outputs.output }}
            LICENSE*
      - name: Notify release
        id: release-notification
        run: |
          echo 'released=true' >> $GITHUB_OUTPUT
