name: Generate OpenAPI Document

on:
  workflow_call:
    inputs:
      openapi-command:
        type: string
        required: true
      project:
        type: string
        required: true
      dotnet-version:
        type: string
        required: true
      output-file:
        type: string
        required: false
        default: 'openapi.json'
      build-artifact-name:
        type: string
        required: true
      openapi-artifact-name:
        type: string
        required: true

jobs:
  generate:
    name: Generate OpenAPI Document
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Download Build artifacts
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.build-artifact-name }}
      - id: generate
        name: Generate OpenAPI Document
        uses: EasyDesk/action-dotnet@v1
        with:
          script: |
            ${{ inputs.openapi-command }} > "${{ inputs.output-file }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.openapi-artifact-name }}
          path: ${{ inputs.output-file }}
